import axios from 'axios';
import { useState } from 'react';

import Head from 'next/head';
import Image from 'next/image';

import { MovieCard, Search, Nav, Hero } from '../components';
import Category from '../components/Category';

const Home = ({ actionMovies, adventureMovies }) => {
  console.log(actionMovies.Search);
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />

      <Hero />

      <Search />

      <Category movies={actionMovies.Search} categoryTitle={'Action'} />
      <Category movies={adventureMovies.Search} categoryTitle={'Adventure'} />
    </div>
  );
};

export const getServerSideProps = async () => {
  const apiKey = process.env.API_KEY;
  const { data: actionMovies } = await axios.get(
    `https://www.omdbapi.com/?apikey=${apiKey}&s='action'`
  );
  const { data: adventureMovies } = await axios.get(
    `https://www.omdbapi.com/?apikey=${apiKey}&s='adventure'`
  );

  console.log(actionMovies);

  return {
    props: {
      actionMovies,
      adventureMovies,
    },
  };
};

export default Home;
